# Generated by Django 4.2.7 on 2024-05-03 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('FACTORY', 'Завод'), ('RETAIL_NETWORK', 'Розничная Сеть'), ('INDIVIDUAL_ENTREPRENEUR', 'Индивидуальный Предприниматель')], max_length=30, verbose_name='company_status')),
                ('name', models.CharField(max_length=255, verbose_name='company_name')),
                ('debt', models.FloatField(default=0, verbose_name='debt')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='date_created')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.company', verbose_name='provider')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('country', models.CharField(max_length=50, verbose_name='country')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('street', models.CharField(max_length=100, verbose_name='street')),
                ('house_number', models.CharField(max_length=50, verbose_name='house_number')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_contacts', to='main.company', verbose_name='company_contact')),
            ],
        ),
    ]
